# Generated by Django 5.2.5 on 2026-01-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='usser',
            new_name='user',
        ),
    ]
